<!DOCTYPE html>
<html>
<head>
    <title>This Email generated by Petopia</title>
</head>
<body>
<h4>Hey sir</h4>
<h3>THis is a confirmation message for you with the appointment</h3>
    <h1>{{ $user['name'] }}</h1>
    <p>{{ $user['info'] }}</p>
    <p>Thank you</p>
</body>
</html> 